version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/circleci-python-workshop
    steps:
      - checkout
      - restore_cache:
          keys:
          - py-deps-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: py-deps-{{ checksum "requirements.txt" }}
      - run:
          name: Run Static Analysis
          command: |
            . venv/bin/activate
            flake8 test_fizzbuzz.py
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python test_fizzbuzz.py
